[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysne"
version = "0.1.0"
description = "Spiral-based Nonlinear Equation solver (SPOC & SPOC-INT)"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "pydoe",
]

[tool.setuptools.packages.find]
where = ["src"]
